const {
    getDialect,
    setGlobalDialect,
    createDialect,
    Dialect,
    MySQLDialect,
    PostgreSQLDialect
} = require("../src/db/dialects");

describe("runtime dialects", () => {
    afterEach(() => setGlobalDialect("mysql"));

    test("selects and validates the global dialect", () => {
        expect(getDialect().name).toBe("mysql");
        setGlobalDialect("postgres");
        expect(getDialect().name).toBe("postgres");
        expect(() => setGlobalDialect("sqlite")).toThrow("Unsupported dialect: sqlite");
    });

    test("escapes identifiers and values for mysql and postgres", () => {
        const mysqlDialect = getDialect();
        expect(mysqlDialect.escape("users.id")).toBe("`users`.`id`");
        expect(mysqlDialect.escape("*")).toBe("*");
        expect(mysqlDialect.escapeIdentifierList(["id", "name"])).toBe("id, name");
        expect(mysqlDialect.escapeValue("O'Reilly")).toContain("O\\'Reilly");
        expect(mysqlDialect.getPlaceholder()).toBe("?");
        expect(() => mysqlDialect.escape("bad-name")).toThrow("Invalid SQL identifier");

        setGlobalDialect("postgres");
        const postgresDialect = getDialect();
        expect(postgresDialect.escape("users.id")).toBe('"users"."id"');
        expect(postgresDialect.escapeValue(null)).toBe("NULL");
        expect(postgresDialect.escapeValue(4)).toBe("4");
        expect(postgresDialect.escapeValue(true)).toBe("TRUE");
        expect(postgresDialect.escapeValue("O'Reilly")).toBe("'O''Reilly'");
        expect(postgresDialect.getPlaceholder(2)).toBe("$3");
    });

    test("formats runtime defaults, executes queries and counts affected rows", async () => {
        const mysqlDialect = getDialect();
        const mysqlDefaults = [
            [undefined, undefined, null],
            [null, undefined, "DEFAULT NULL"],
            [() => 7, "int", "DEFAULT 7"],
            [() => new Date("2024-01-02T03:04:05Z"), "date", "DEFAULT CURRENT_TIMESTAMP"],
            [new Date("2024-01-02T03:04:05Z"), undefined, 'DEFAULT "2024-01-02 03:04:05"'],
            ["now()", undefined, "DEFAULT CURRENT_TIMESTAMP"],
            ["O'Reilly", undefined, 'DEFAULT "O\'Reilly"'],
            [3n, undefined, "DEFAULT 3"],
            [true, undefined, "DEFAULT 1"],
            [{ active: true }, undefined, 'DEFAULT "{""active"":true}"']
        ];
        for (const [value, type, expected] of mysqlDefaults) {
            expect(mysqlDialect.formatDefaultSql(value, type)).toBe(expected);
        }
        expect(mysqlDialect.extractUuid([{ "UUID()": "mysql-id" }])).toBe("mysql-id");
        expect(mysqlDialect.extractUuid({ "UUID()": "fallback" })).toBe("fallback");
        expect(mysqlDialect.countKey({ count: 2 })).toBe(2);
        expect(mysqlDialect.countKey({ value: 3 })).toBe(3);

        const mysqlConnection = { promise: () => ({ execute: jest.fn().mockResolvedValue([[{ id: 1 }]]) }) };
        await expect(mysqlDialect.execute(mysqlConnection, "SELECT ?", [1])).resolves.toEqual([{ id: 1 }]);
        expect(mysqlDialect.getAffectedRows({ affectedRows: 2 })).toBe(2);
        expect(mysqlDialect.getAffectedRows({})).toBe(0);

        setGlobalDialect("postgres");
        const postgresDialect = getDialect();
        expect(postgresDialect.formatDefaultSql(undefined)).toBeNull();
        expect(postgresDialect.formatDefaultSql(null)).toBe("DEFAULT NULL");
        expect(postgresDialect.formatDefaultSql(() => 7)).toBe("DEFAULT 7");
        expect(postgresDialect.formatDefaultSql(() => new Date(), "datetime")).toBe("DEFAULT CURRENT_TIMESTAMP");
        expect(postgresDialect.formatDefaultSql(new Date("2024-01-02T03:04:05Z"))).toBe("DEFAULT '2024-01-02 03:04:05'");
        expect(postgresDialect.formatDefaultSql("CURRENT_TIMESTAMP()", "date")).toBe("DEFAULT CURRENT_TIMESTAMP");
        expect(postgresDialect.formatDefaultSql("O'Reilly")).toBe("DEFAULT 'O''Reilly'");
        expect(postgresDialect.formatDefaultSql(3n)).toBe("DEFAULT 3");
        expect(postgresDialect.formatDefaultSql(false)).toBe("DEFAULT FALSE");
        expect(postgresDialect.formatDefaultSql({ active: true })).toBe("DEFAULT '{\"active\":true}'");
        expect(postgresDialect.autoIncrement('Number')).toBe('GENERATED BY DEFAULT AS IDENTITY');
        expect(() => postgresDialect.autoIncrement('String')).toThrow('PostgreSQL auto-increment is unsupported for type String.');
        expect(postgresDialect.extractUuid([{ uuid: "pg-id" }])).toBe("pg-id");
        expect(postgresDialect.extractUuid({ uuid: "fallback" })).toBe("fallback");
        expect(postgresDialect.countKey({ count: 2 })).toBe(2);

        const query = jest.fn().mockResolvedValue({ rows: [{ id: 1 }], rowCount: 1 });
        const rows = await postgresDialect.execute({ query }, "SELECT ?", [1]);
        expect(query).toHaveBeenCalledWith("SELECT $1", [1]);
        expect(rows[0]).toEqual({ id: 1 });
        expect(rows.rowCount).toBe(1);
        expect(postgresDialect.getAffectedRows({ rowCount: 4 })).toBe(4);
        expect(postgresDialect.getAffectedRows({})).toBe(0);
    });

    test("covers runtime fallback branches", async () => {
        const mysqlDialect = getDialect();
        expect(mysqlDialect.formatDefaultSql(false)).toBe("DEFAULT 0");
        expect(mysqlDialect.formatDefaultSql(Symbol("value"))).toBe('DEFAULT "Symbol(value)"');
        const promiseConnection = {
            promise: () => ({ execute: jest.fn().mockResolvedValue([[{ id: 2 }]]) })
        };
        await expect(mysqlDialect.execute(promiseConnection, "SELECT 1")).resolves.toEqual([{ id: 2 }]);
    });
});

describe("migration dialect base class", () => {
    class TestDialect extends Dialect {}

    test("provides common SQL helpers and abstract errors", async () => {
        const defaultDialect = new Dialect("default");
        const dialect = new TestDialect("test", { quote: "`" });
        const concreteDialect = new (class extends TestDialect {
            columnDefinition(name) {
                return this.escape(name) + " TEXT";
            }
        })("test", { quote: "`" });
        expect(dialect.escape("users")).toBe("`users`");
        expect(dialect.placeholder()).toBe("?");
        expect(dialect.placeholders(3)).toBe("?, ?, ?");
        expect(concreteDialect.addColumn("users", "name", {})).toContain("ADD COLUMN");
        expect(dialect.renameColumn("users", "old", "new")).toContain("RENAME COLUMN");
        expect(dialect.dropColumn("users", "name")).toContain("DROP COLUMN");
        expect(dialect.dropTable("users")).toBe("DROP TABLE `users`;");
        expect(dialect.normalizeDatabaseColumn({ id: 1 })).toEqual({ id: 1 });
        expect(dialect.normalizeDatabaseTable({ name: "users" })).toEqual({ name: "users" });
        await expect(defaultDialect.begin()).resolves.toBeUndefined();
        await expect(defaultDialect.commit()).resolves.toBeUndefined();
        await expect(defaultDialect.rollback()).resolves.toBeUndefined();
        await expect(dialect.transaction({}, () => "result")).resolves.toBe("result");
        expect(() => dialect.execute()).toThrow("test dialect must implement execute().");
        expect(() => dialect.mapType()).toThrow("test dialect must implement mapType().");
        expect(() => dialect.columnDefinition()).toThrow("test dialect must implement columnDefinition().");
        expect(() => dialect.createTable()).toThrow("test dialect must implement createTable().");
        expect(() => dialect.alterColumn()).toThrow("test does not implement alterColumn().");
        expect(() => dialect.introspectionQueries()).toThrow("test dialect must implement introspectionQueries().");
        expect(() => dialect.createMigrationTable()).toThrow("test dialect must implement createMigrationTable().");
        expect(() => dialect.insertMigration()).toThrow("test dialect must implement insertMigration().");
        expect(() => dialect.selectMigrations()).toThrow("test dialect must implement selectMigrations().");
        expect(() => dialect.deleteMigration()).toThrow("test dialect must implement deleteMigration().");
    });

    test("runs transactional callbacks and rolls back failures", async () => {
        const dialect = new TestDialect("test", { capabilities: { transactionalDDL: true } });
        dialect.begin = jest.fn();
        dialect.commit = jest.fn();
        dialect.rollback = jest.fn();
        await expect(dialect.transaction("connection", () => "done")).resolves.toBe("done");
        expect(dialect.begin).toHaveBeenCalledWith("connection");
        expect(dialect.commit).toHaveBeenCalledWith("connection");
        dialect.rollback.mockRejectedValueOnce(new Error("rollback failed"));
        await expect(dialect.transaction("connection", () => { throw new Error("query failed"); })).rejects.toThrow("query failed");
        expect(dialect.rollback).toHaveBeenCalledWith("connection");
    });
});

const MYSQL_TYPES = [
    ["STRING", "VARCHAR(10)"], ["VARCHAR", "VARCHAR(10)"], ["CHAR", "CHAR(10)"], ["TEXT", "TEXT"],
    ["NUMBER", "INT"], ["INT", "INT"], ["INTEGER", "INT"], ["SMALLINT", "SMALLINT"], ["MEDIUMINT", "MEDIUMINT"],
    ["BIGINT", "BIGINT"], ["DECIMAL", "DECIMAL"], ["NUMERIC", "DECIMAL"], ["FLOAT", "DOUBLE"], ["DOUBLE", "DOUBLE"],
    ["BOOLEAN", "BOOLEAN"], ["BOOL", "BOOLEAN"], ["TINYINT", "BOOLEAN"], ["DATE", "DATE"], ["DATETIME", "DATETIME"],
    ["TIMESTAMP", "DATETIME"], ["NOW", "DATETIME"], ["CURRENTTIMESTAMP", "DATETIME"], ["OBJECT", "JSON"], ["JSON", "JSON"],
    ["BLOB", "BLOB"], ["VARBINARY", "VARBINARY"], ["BINARY", "VARBINARY"]
];

const POSTGRES_TYPES = [
    ["STRING", "VARCHAR(10)"], ["VARCHAR", "VARCHAR(10)"], ["CHARACTER VARYING", "VARCHAR(10)"], ["CHAR", "CHAR(10)"],
    ["BPCHAR", "CHAR(10)"], ["CHARACTER", "CHAR(10)"], ["TEXT", "TEXT"], ["NUMBER", "INTEGER"], ["INT", "INTEGER"],
    ["INT4", "INTEGER"], ["INTEGER", "INTEGER"], ["SMALLINT", "SMALLINT"], ["INT2", "SMALLINT"], ["BIGINT", "BIGINT"],
    ["INT8", "BIGINT"], ["DECIMAL", "DECIMAL"], ["NUMERIC", "DECIMAL"], ["FLOAT", "REAL"], ["FLOAT4", "REAL"], ["REAL", "REAL"],
    ["DOUBLE", "DOUBLE PRECISION"], ["FLOAT8", "DOUBLE PRECISION"], ["DOUBLE PRECISION", "DOUBLE PRECISION"], ["BOOLEAN", "BOOLEAN"],
    ["BOOL", "BOOLEAN"], ["DATE", "DATE"], ["DATETIME", "TIMESTAMP"], ["TIMESTAMP", "TIMESTAMP"], ["NOW", "TIMESTAMP"],
    ["CURRENTTIMESTAMP", "TIMESTAMP"], ["TIMESTAMPTZ", "TIMESTAMPTZ"], ["TIMESTAMP WITH TIME ZONE", "TIMESTAMPTZ"], ["OBJECT", "JSONB"],
    ["JSON", "JSONB"], ["JSONB", "JSONB"], ["UUID", "UUID"]
];

describe("migration dialect implementations", () => {
    test("maps MySQL types and builds schema SQL", async () => {
        const dialect = new MySQLDialect();
        expect(dialect.placeholder()).toBe("?");
        await expect(dialect.execute({
            query: (sql, values, callback) => callback(null, [{ id: 1 }])
        }, "SELECT ?", [1])).resolves.toEqual([{ id: 1 }]);
        await expect(dialect.execute({
            query: (sql, values, callback) => callback(new Error("query failed"))
        }, "SELECT ?", [1])).rejects.toThrow("query failed");
        await expect(dialect.execute({
            promise: () => ({ query: jest.fn().mockResolvedValue([[{ id: 2 }]]) })
        }, "SELECT ?", [1])).resolves.toEqual([{ id: 2 }]);
        await expect(dialect.execute({
            promise: () => ({ query: jest.fn().mockResolvedValue([[{ id: 3 }]]) })
        }, "SELECT 1")).resolves.toEqual([{ id: 3 }]);
        for (const [type, expected] of MYSQL_TYPES) expect(dialect.mapType({ type, length: 10 })).toBe(expected);
        expect(() => dialect.mapType({ type: "unknown" })).toThrow("Unsupported MySQL type");
        expect(() => dialect.mapType({})).toThrow("Unsupported MySQL type: undefined");
        expect(dialect.defaultSql(undefined)).toBe("");
        expect(dialect.defaultSql(null)).toBe("DEFAULT NULL");
        expect(dialect.defaultSql(2)).toBe("DEFAULT 2");
        expect(dialect.defaultSql(true)).toBe("DEFAULT 1");
        expect(dialect.defaultSql(false)).toBe("DEFAULT 0");
        expect(dialect.defaultSql("O'Reilly")).toBe("DEFAULT 'O''Reilly'");
        expect(dialect.defaultSql("CURRENT_DATE")).toBe("DEFAULT CURRENT_DATE");
        expect(dialect.defaultSql({ value: 1 })).toContain("DEFAULT");
        const field = { type: "string", length: 20, required: true, default: "x", unique: true, customize: "CHECK (1)" };
        expect(dialect.columnDefinition("name", field)).toContain("`name` VARCHAR(20) NOT NULL");
        expect(() => dialect.columnDefinition("id", { type: "int", primary_key: true, unique: true })).toThrow();
        expect(dialect.columnDefinition("id", { type: "int", primary_key: true, auto_increment: true })).toContain("AUTO_INCREMENT PRIMARY KEY");
        expect(dialect.createTable("users", { id: { type: "int", primary_key: true }, user_id: { type: "int", foreignKey: "users(id)" } })).toContain("FOREIGN KEY");
        expect(dialect.createTable("users", { user_id: { type: "int", foreignKey: "users.id" } })).toContain("FOREIGN KEY");
        expect(() => dialect.createTable("users", { user_id: { type: "int", foreignKey: "invalid key" } })).toThrow();
        expect(dialect.alterColumn("users", "name", { type: "string" })).toContain("MODIFY COLUMN");
        expect(dialect.introspectionQueries().columns).toContain("ORDINAL_POSITION");
        expect(dialect.normalizeDatabaseColumn({ data_type: "varchar", character_maximum_length: 10, is_nullable: "NO", column_key: "PRI", extra: "auto_increment", column_default: "x" })).toEqual(expect.objectContaining({ type: "varchar", length: 10, required: true, primary_key: true, auto_increment: true }));
        expect(dialect.normalizeDatabaseColumn({})).toEqual(expect.objectContaining({ type: "", length: undefined, auto_increment: false }));
        expect(dialect.createMigrationTable()).toContain("sql_connector_migrations");
        expect(dialect.insertMigration()).toContain("VALUES (?, ?, ?, ?)");
        expect(dialect.selectMigrations()).toContain("ORDER BY");
        expect(dialect.deleteMigration()).toContain("WHERE");
    });

    test("maps PostgreSQL types and builds schema SQL", async () => {
        const dialect = new PostgreSQLDialect();
        expect(dialect.placeholder(2)).toBe("$3");
        for (const [type, expected] of POSTGRES_TYPES) expect(dialect.mapType({ type, length: 10 })).toBe(expected);
        expect(() => dialect.mapType({ type: "unknown" })).toThrow("Unsupported PostgreSQL type");
        expect(() => dialect.mapType({})).toThrow("Unsupported PostgreSQL type: undefined");
        expect(dialect.defaultSql(undefined)).toBe("");
        expect(dialect.defaultSql(null)).toBe("DEFAULT NULL");
        expect(dialect.defaultSql(2)).toBe("DEFAULT 2");
        expect(dialect.defaultSql(false)).toBe("DEFAULT FALSE");
        expect(dialect.defaultSql(true)).toBe("DEFAULT TRUE");
        expect(dialect.defaultSql("O'Reilly")).toBe("DEFAULT 'O''Reilly'");
        expect(dialect.defaultSql("CURRENT_TIME")).toBe("DEFAULT CURRENT_TIME");
        expect(dialect.defaultSql({ value: 1 })).toContain("DEFAULT");
        expect(dialect.columnDefinition("id", { type: "int", primary_key: true, auto_increment: true, customize: "CHECK (id > 0)" })).toContain("CHECK (id > 0)");
        expect(dialect.columnDefinition("name", { type: "string", default: "x", unique: true })).toContain("UNIQUE");
        expect(() => dialect.columnDefinition("id", { type: "int", primary_key: true, unique: true })).toThrow();
        expect(dialect.createTable("users", { name: { type: "string" }, user_id: { type: "int", foreignKey: "users.id" } })).toContain("FOREIGN KEY");
        expect(() => dialect.createTable("users", { user_id: { type: "int", foreignKey: "invalid key" } })).toThrow();
        expect(dialect.alterColumn("users", "name", { type: "string", required: true, default: "x" })).toContain("SET NOT NULL");
        expect(dialect.alterColumn("users", "name", { type: "string" })).toContain("DROP NOT NULL");
        expect(dialect.introspectionQueries().columns).toContain("ordinal_position");
        expect(dialect.normalizeDatabaseColumn({ udt_name: "int4", is_nullable: "NO", column_default: "nextval('x')" })).toEqual(expect.objectContaining({ type: "int4", required: true, auto_increment: true }));
        expect(dialect.normalizeDatabaseColumn({ data_type: "varchar", column_default: null })).toEqual(expect.objectContaining({ type: "varchar", auto_increment: false }));
        expect(dialect.normalizeDatabaseColumn({})).toEqual(expect.objectContaining({ type: "", auto_increment: false }));
        expect(dialect.createMigrationTable()).toContain("TIMESTAMPTZ");
        expect(dialect.insertMigration()).toContain("VALUES ($1, $2, $3, $4)");
        expect(dialect.selectMigrations()).toContain("ORDER BY");
        expect(dialect.deleteMigration()).toContain("WHERE");
        expect(() => dialect.execute({}, "SELECT 1")).toThrow("does not expose query");
        await expect(dialect.execute({ query: jest.fn().mockResolvedValue({ rows: [{ id: 1 }] }) }, "SELECT 1")).resolves.toEqual([{ id: 1 }]);
    });
});

describe("createDialect", () => {
    test("creates supported aliases and rejects unknown dialects", () => {
        expect(createDialect("mysql")).toBeInstanceOf(MySQLDialect);
        expect(createDialect("mariadb")).toBeInstanceOf(MySQLDialect);
        expect(createDialect("postgres")).toBeInstanceOf(PostgreSQLDialect);
        expect(createDialect("postgresql")).toBeInstanceOf(PostgreSQLDialect);
        expect(createDialect("POSTGRES")).toBeInstanceOf(PostgreSQLDialect);
        setGlobalDialect("postgres");
        expect(createDialect()).toBeInstanceOf(PostgreSQLDialect);
        expect(() => createDialect("sqlite")).toThrow("Unsupported migration dialect");
    });
});