name: Publish Package

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  check_security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
      - name: setup node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38
        with:
          node-version: 22
      - name: Install deps
        run: npm ci
      - name: Audit deps
        continue-on-error: false
        run: |
          npm audit
      - name: Check security of module
        continue-on-error: false
        run: |
          npm run security
  integrity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
      - name: setup node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38
        with:
          node-version: 22
      - name: Install deps
        run: npm ci
      - name: Run integrity check
        continue-on-error: false
        run: |
          npm run test
  publish:
    needs:
      - check_security
      - integrity
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: sqlc
    permissions:
      contents: read
      id-token: write # Requis pour la provenance (--provenance)

    steps:
      # 1. Récupérer le code source
      - name: Checkout du code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803

      # 2. Configurer Node.js pour registry.npmjs.org
      - name: Configurer Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org/"
          scope: "@mlagie"

      # 3. Installer les dépendances
      - name: Installer les dépendances
        run: npm ci

      # 4. Publier sur le vrai registre npm
      - name: Publier sur npmjs.com
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
